'use strict';
// Assessment registry. Every recording is bound to exactly one known {testId, testVersion, questionCount}
// tuple; the host and validators keep the same table. practice-js-5 v1 is the original assessment: its
// questions and grading must never change, because recordings made before test selection map to it.
// A changed question set needs a new testVersion (or testId) in every table, never an edit in place.
(() => {
 const original = [
 {id:'arithmetic',type:'Multiple choice',title:'A small calculation',prompt:'Choose the value of 7 + 5.',options:['10','11','12','13'],answer:'12'},
 {id:'blank',type:'Fill in the blank',title:'Array length',prompt:'An array contains [4, 8, 12, 16, 20]. How many elements does it contain? Enter one number.',answer:'5'},
 {id:'loop',type:'Dropdown',title:'At least one iteration',prompt:'Which JavaScript loop checks its condition after executing the body?',options:['for','while','do...while'],answer:'do...while'},
 {id:'summary',type:'Coding',title:'Number summary',fn:'summarize',prompt:'Write a JavaScript function summarize(numbers). Return an object with four properties: count, sum, evenCount, and max. Use a loop to examine the input. For an empty array, return count 0, sum 0, evenCount 0, and max null. Do not modify the input array. This is an easy problem; take your time to format the code clearly.',details:['Input: an array of integers, including negative numbers and zero.','count: the number of elements.','sum: the total of all numbers.','evenCount: the count of numbers divisible by two, including zero.','max: the largest number, or null for an empty array.','Create local variables, loop through the array, then return the result. You may use any equivalent correct implementation.','No network requests, file access, libraries or console interaction are required.','Before submitting, run the tests. Read failing examples and correct your solution.'],example:'summarize([3, 6, -2, 0])\n→ {count: 4, sum: 7, evenCount: 3, max: 6}',starter:'function summarize(numbers) {\n    // Build your result here.\n\n}\n',tests:[{input:[[]],out:{count:0,sum:0,evenCount:0,max:null}},{input:[[3,6,-2,0]],out:{count:4,sum:7,evenCount:3,max:6}},{input:[[-5,-3,-7]],out:{count:3,sum:-15,evenCount:0,max:-3}},{input:[[2]],out:{count:1,sum:2,evenCount:1,max:2}},{input:[[1,2,3,4,5]],out:{count:5,sum:15,evenCount:2,max:5}}]},
 {id:'receipt',type:'Coding',title:'Format a shopping receipt',fn:'makeReceipt',prompt:'Write a JavaScript function makeReceipt(items). Each item has a name and an integer price. Return a string with one line per item, followed by a total line. Keep input order. Use exactly the formatting shown below. An empty array returns "TOTAL: 0".',details:['Each input item looks like {name: "Pen", price: 3}.','An item line is its name, a colon, one space, then its price.','After the items, append TOTAL: followed by one space and the sum of prices.','Separate lines with a newline character (\\n).','Do not add a newline after the last line.','Prices are non-negative integers. Names are non-empty strings.','A loop and an array of lines can help. Return the completed string.','Test empty input as well as a list with several items.'],example:'makeReceipt([{name:"Pen",price:3},{name:"Book",price:7}])\n→ "Pen: 3\\nBook: 7\\nTOTAL: 10"',starter:'function makeReceipt(items) {\n    // Format one line per item and add the total.\n\n}\n',tests:[{input:[[]],out:'TOTAL: 0'},{input:[[{name:'Pen',price:3},{name:'Book',price:7}]],out:'Pen: 3\nBook: 7\nTOTAL: 10'},{input:[[{name:'Gift',price:0}]],out:'Gift: 0\nTOTAL: 0'},{input:[[{name:'A',price:10},{name:'B',price:2},{name:'C',price:4}]],out:'A: 10\nB: 2\nC: 4\nTOTAL: 16'}]}
 ];
 const extended = [
 {id:'x-modulo',type:'Multiple choice',title:'Remainder',prompt:'What is the value of 17 % 5 in JavaScript?',options:['2','3','4','5'],answer:'2'},
 {id:'x-typeof-array',type:'Multiple choice',title:'Type of an array',prompt:'What does typeof [] return?',options:['array','object','list','undefined'],answer:'object'},
 {id:'x-strict-equality',type:'Multiple choice',title:'Strict equality',prompt:'Which expression evaluates to true?',options:["'5' === 5",'null === undefined','3 === 3','NaN === NaN'],answer:'3 === 3'},
 {id:'x-push-return',type:'Multiple choice',title:'Array push',prompt:'After const a = [1, 2]; what does a.push(9) return?',options:['[1, 2, 9]','3','9','undefined'],answer:'3'},
 {id:'x-const',type:'Multiple choice',title:'Fixed binding',prompt:'Which keyword declares a variable that cannot be reassigned?',options:['var','let','const','static'],answer:'const'},
 {id:'x-string-index',type:'Multiple choice',title:'String index',prompt:"What is the value of 'calibrate'[2]?",options:['a','l','i','c'],answer:'l'},
 {id:'x-slice',type:'Multiple choice',title:'Array slice',prompt:'What does [10, 20, 30, 40].slice(1, 3) return?',options:['[10, 20]','[20, 30]','[20, 30, 40]','[30, 40]'],answer:'[20, 30]'},
 {id:'x-loop-count',type:'Multiple choice',title:'Loop iterations',prompt:'How many times does the body of for (let i = 0; i < 4; i++) { } run?',options:['3','4','5','It never stops'],answer:'4'},
 {id:'x-boolean',type:'Multiple choice',title:'Boolean logic',prompt:'What is the value of !(true && false)?',options:['true','false','undefined','null'],answer:'true'},
 {id:'x-math-max',type:'Multiple choice',title:'Largest value',prompt:'What does Math.max(3, 11, 7) return?',options:['3','7','11','21'],answer:'11'},
 {id:'x-count-vowels',type:'Coding',title:'Count the vowels',fn:'countVowels',prompt:'Write a JavaScript function countVowels(text). Return how many characters in text are vowels: a, e, i, o or u, in upper or lower case. Return 0 for an empty string. This is an easy problem; take your time to format the code clearly.',details:['Input: a string that may contain letters, spaces and punctuation.','Count only a, e, i, o and u. The letter y is not a vowel here.','Upper-case vowels count too: "A" and "a" are both vowels.','Return a number, not a string.','A loop over the characters and a counter is enough. You may use any equivalent correct implementation.','No network requests, file access, libraries or console interaction are required.','Before submitting, run the tests. Read failing examples and correct your solution.'],example:'countVowels("Hello, World!")\n→ 3',starter:'function countVowels(text) {\n    // Count the vowels here.\n\n}\n',tests:[{input:[''],out:0},{input:['Hello, World!'],out:3},{input:['calibration'],out:5},{input:['RHYTHM'],out:0},{input:['AEIOU aeiou'],out:10}]},
 {id:'x-reverse-words',type:'Coding',title:'Reverse the words',fn:'reverseWords',prompt:'Write a JavaScript function reverseWords(sentence). The sentence contains words separated by single spaces. Return a new string with the same words in reverse order, separated by single spaces. An empty string returns an empty string.',details:['Input: words separated by exactly one space, with no leading or trailing spaces.','Reverse the order of the words, not the letters inside each word.','Keep each word exactly as written, including capital letters and punctuation.','A single word is returned unchanged.','Splitting on spaces and joining with spaces can help. You may use any equivalent correct implementation.','No network requests, file access, libraries or console interaction are required.','Before submitting, run the tests. Read failing examples and correct your solution.'],example:'reverseWords("practice makes progress")\n→ "progress makes practice"',starter:'function reverseWords(sentence) {\n    // Return the words in reverse order.\n\n}\n',tests:[{input:[''],out:''},{input:['practice makes progress'],out:'progress makes practice'},{input:['one'],out:'one'},{input:['a b c d'],out:'d c b a'},{input:['Hello, big World!'],out:'World! big Hello,'}]},
 {id:'x-count-above',type:'Coding',title:'Count values above a limit',fn:'countAbove',prompt:'Write a JavaScript function countAbove(numbers, limit). Return how many values in numbers are strictly greater than limit. Values equal to limit do not count. Return 0 for an empty array. Do not modify the input array.',details:['Input: an array of integers, including negative numbers and zero, and an integer limit.','Strictly greater means value > limit; a value equal to limit is not counted.','Return a number.','A loop with a counter is enough. You may use any equivalent correct implementation.','No network requests, file access, libraries or console interaction are required.','Before submitting, run the tests. Read failing examples and correct your solution.'],example:'countAbove([1, 5, 9], 4)\n→ 2',starter:'function countAbove(numbers, limit) {\n    // Count the values greater than limit.\n\n}\n',tests:[{input:[[],0],out:0},{input:[[1,5,9],4],out:2},{input:[[7,7,7],7],out:0},{input:[[-3,-1,0],-2],out:2},{input:[[10,20,30],0],out:3}]}
 ];
 const freeze = value => { if (value && typeof value === 'object' && !Object.isFrozen(value)) { Object.freeze(value); Object.values(value).forEach(freeze); } return value; };
 window.assessments = freeze([
  {testId:'practice-js-5',testVersion:1,questionCount:5,name:'Original practice',composition:'3 basics · 2 coding',questions:original},
  {testId:'practice-js-13',testVersion:1,questionCount:13,name:'Extended practice',composition:'10 multiple choice · 3 coding',questions:extended}
 ]);
 // Legacy alias: the original question list, as before test selection existed.
 window.questions = original;
})();
